### ISSUE TITLE
Redirect Error

### ISSUE THREAD

**Issue by derevandal** [Wonderfall/docker-nextcloud#28]
Hi, 

I deploy a stack on my swarm with this compose:

```yml
version: '3'

networks:
  nextcloud_network:
    external: false
  proxy_private:
    external: true

volumes:
  nextcloud-data:
  nextcloud-db:
  nextcloud-redis:
  nextcloud-config:
  nextcloud-apps:
  nextcloud-themes:

services:
  nextcloud:
    image: wonderfall/nextcloud
    depends_on:
      - mariadb                # If using MySQL
      - redis                  # If using Redis
    environment:
      - UID=1000
      - GID=1000
      - UPLOAD_MAX_SIZE=10G
      - APC_SHM_SIZE=128M
      - OPCACHE_MEM_SIZE=128
      - CRON_PERIOD=15m
      - TZ=America/Sao_Paulo
      - DOMAIN=cloud.domain.com
      - DB_TYPE=mysql
      - DB_NAME=nextcloud
      - DB_USER=nextcloud
      - DB_PASSWORD=supersecretpassword
      - DB_HOST=mariadb
      - ADMIN_USER=admin           # Don't set to configure through browser
      - ADMIN_PASSWORD=admin  
    volumes:
      - 'nextcloud-data:/data'
      - 'nextcloud-config:/config'
      - 'nextcloud-apps:/apps2'
      - 'nextcloud-themes:/nextcloud/themes'
    networks:
      - nextcloud_network
      - proxy_private
    deploy:
      placement: {constraints: ['node.labels.type == nextcloud']}
      update_config: {parallelism: 1, delay: 10s}
      restart_policy: {condition: on-failure}
      labels: 
        - caddy.address=cloud.domain.com
        - caddy.targetport=8888

  # If using MySQL

  mariadb:
    image: bianjp/mariadb-alpine
    environment:
      MYSQL_ROOT_PASSWORD: supersecretpassword
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: supersecretpassword
    volumes:
      - nextcloud-db:/var/lib/mysql
    networks:
      - nextcloud_network
    deploy:
      placement: {constraints: ['node.labels.type == nextcloud']}
      update_config: {parallelism: 1, delay: 10s}
      restart_policy: {condition: on-failure}

  # If using Redis
  redis:
    image: redis:alpine
    volumes:
      - nextcloud-redis:/data
    networks:
      - nextcloud_network
    deploy:
      placement: {constraints: ['node.labels.type == nextcloud']}
      update_config: {parallelism: 1, delay: 10s}
      restart_policy: {condition: on-failure}
```
And i'm using caddy as reverse proxy.

After successfully installation, Nextcloud redirects me to http://nextcloud_nextcloud:8888/apps/files/ instead of https://cloud.domain.com/apps/files/

Cloud u help me?
