### ISSUE TITLE
Nextcloud is not installed - only a limited number of commands are available

### ISSUE THREAD

**Issue by infa-presales** [Wonderfall/docker-nextcloud#90]
Actually, it is not a real "migration" issue, as I give up migrating instances based on an elder image to the recent. Instead, I created a brand new environment with a docker-compose.yml. I tried both, downloading the latest image 22.1.0 ghcr.io/wonderfall/nextcloud:22 and building it from scratch, but on both versions I had the same issue:
In both cases - as in earlier versions from this year - even a fresh created instance does not initialize as given in the environment variables of docker-compose.yml. 

Nextcloud container always comes up with a partially installed nextcloud, in the logs with messages like this. 

```nextcloud      | Starting automatic configuration...
nextcloud       | Automatic configuration finished.
nextcloud       | Nextcloud is not installed - only a limited number of commands are available
nextcloud       |
nextcloud       |
nextcloud       |  Command "app:disable" is not defined.
nextcloud       |
nextcloud       |
nextcloud       |  Do you want to run "app:check-code" instead?  (yes/no) [no]:
```

The docker-compose.yml is 
```yml
version: '3'

networks:
  internal:
    external: false
  extern:
    external: true

services:
  db_nextcloud:
    container_name: db_nextcloud
    image: mariadb:10
    volumes:
      - ../volumes/db_nextcloud:/var/lib/mysql/
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=MYDBROOTPASSWORD
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=MYDBPASSWORD
    restart: unless-stopped
    command: ['--innodb_read_only_compressed=OFF'] # added because of https://help.nextcloud.com/t/update-to-next-cloud-21-0-2-has-get-an-error/117028/27
    networks:
      - internal

  nextcloud:
    container_name: nextcloud
    # see https://github.com/Wonderfall/docker-nextcloud/pkgs/container/nextcloud for latest versions
    image: ghcr.io/wonderfall/nextcloud:22
    #build:
    #  context: ./docker-nextcloud
    depends_on:
      - db_nextcloud
    environment:
      - UID=1000
      - GID=1000
      - UPLOAD_MAX_SIZE=10G
      - APC_SHM_SIZE=128M
      - OPCACHE_MEM_SIZE=128
      - CRON_PERIOD=15m
      - TZ=Etc/UTC
      - ADMIN_USER=admin
      - ADMIN_PASSWORD=MYADMINPASSWD
      - DOMAIN=my.fqdn
      - DB_TYPE=mysql
      - DB_NAME=nextcloud
      - DB_USER=nextcloud
      - DB_PASSWORD=DBPASSWORD
      - DB_HOST=db_nextcloud
      - VIRTUAL_HOST=my.fqdn
    networks:
      - extern
      - internal
    volumes:
      - /var/lib/nextcloud/data:/data
      - ../volumes/nextcloud/config:/nextcloud/config
      - ../volumes/nextcloud/apps2:/nextcloud/apps2
      - ../volumes/nextcloud/themes:/nextcloud/themes
    labels:
      - "traefik.enable=true"
      - traefik.http.routers.nextcloud.rule=Host(`my.fqdn`) 
      - "traefik.http.routers.nextcloud.tls.certResolver=default"
      - "traefik.http.routers.nextcloud.tls=true"
```

Here the docker-compose output on `docker-compose up` after cleansing the volumes:

```
Building with native build. Learn about native build in Compose here: https://docs.docker.com/go/compose-native-build/
Creating network "compose_internal" with the default driver
Creating db_nextcloud ... done
Creating nextcloud    ... done
Attaching to nextcloud, db_nextcloud
db_nextcloud    | 2021-08-28 18:38:18+02:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.6.4+maria~focal started.
db_nextcloud    | 2021-08-28 18:38:18+02:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
db_nextcloud    | 2021-08-28 18:38:18+02:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.6.4+maria~focal started.
db_nextcloud    | 2021-08-28 18:38:19+02:00 [Note] [Entrypoint]: Initializing database files
db_nextcloud    | 2021-08-28 18:38:19 0 [Warning] You need to use --log-bin to make --expire-logs-days or --binlog-expire-logs-seconds work.
nextcloud       | Starting automatic configuration...
nextcloud       | Automatic configuration finished.
nextcloud       | Nextcloud is not installed - only a limited number of commands are available
nextcloud       |
nextcloud       |
nextcloud       |  Command "app:disable" is not defined.
nextcloud       |
nextcloud       |
nextcloud       |  Do you want to run "app:check-code" instead?  (yes/no) [no]:
db_nextcloud    |
db_nextcloud    |
db_nextcloud    | PLEASE REMEMBER TO SET A PASSWORD FOR THE MariaDB root USER !
db_nextcloud    | To do so, start the server, then issue the following command:
db_nextcloud    |
db_nextcloud    | '/usr/bin/mysql_secure_installation'
db_nextcloud    |
db_nextcloud    | which will also give you the option of removing the test
db_nextcloud    | databases and anonymous user created by default.  This is
db_nextcloud    | strongly recommended for production servers.
db_nextcloud    |
db_nextcloud    | See the MariaDB Knowledgebase at https://mariadb.com/kb or the
db_nextcloud    | MySQL manual for more instructions.
db_nextcloud    |
db_nextcloud    | Please report any problems at https://mariadb.org/jira
db_nextcloud    |
db_nextcloud    | The latest information about MariaDB is available at https://mariadb.org/.
db_nextcloud    | You can find additional information about the MySQL part at:
db_nextcloud    | https://dev.mysql.com
db_nextcloud    | Consider joining MariaDB's strong and vibrant community:
db_nextcloud    | https://mariadb.org/get-involved/
db_nextcloud    |
db_nextcloud    | 2021-08-28 18:38:21+02:00 [Note] [Entrypoint]: Database files initialized
db_nextcloud    | 2021-08-28 18:38:21+02:00 [Note] [Entrypoint]: Starting temporary server
db_nextcloud    | 2021-08-28 18:38:21+02:00 [Note] [Entrypoint]: Waiting for server startup
db_nextcloud    | 2021-08-28 18:38:21 0 [Note] mysqld (server 10.6.4-MariaDB-1:10.6.4+maria~focal) starting as process 101 ...
db_nextcloud    | 2021-08-28 18:38:21 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
db_nextcloud    | 2021-08-28 18:38:21 0 [Note] InnoDB: Number of pools: 1
db_nextcloud    | 2021-08-28 18:38:21 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
db_nextcloud    | 2021-08-28 18:38:21 0 [Note] mysqld: O_TMPFILE is not supported on /tmp (disabling future attempts)
db_nextcloud    | 2021-08-28 18:38:21 0 [Note] InnoDB: Using Linux native AIO
db_nextcloud    | 2021-08-28 18:38:21 0 [Note] InnoDB: Initializing buffer pool, total size = 134217728, chunk size = 134217728
db_nextcloud    | 2021-08-28 18:38:21 0 [Note] InnoDB: Completed initialization of buffer pool
db_nextcloud    | 2021-08-28 18:38:21 0 [Note] InnoDB: 128 rollback segments are active.
db_nextcloud    | 2021-08-28 18:38:21 0 [Note] InnoDB: Creating shared tablespace for temporary tables
db_nextcloud    | 2021-08-28 18:38:21 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
db_nextcloud    | 2021-08-28 18:38:21 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
db_nextcloud    | 2021-08-28 18:38:21 0 [Note] InnoDB: 10.6.4 started; log sequence number 42161; transaction id 14
db_nextcloud    | 2021-08-28 18:38:21 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
db_nextcloud    | 2021-08-28 18:38:21 0 [Note] Plugin 'FEEDBACK' is disabled.
db_nextcloud    | 2021-08-28 18:38:21 0 [Warning] You need to use --log-bin to make --expire-logs-days or --binlog-expire-logs-seconds work.
db_nextcloud    | 2021-08-28 18:38:21 0 [Warning] 'user' entry 'root@77cef25aef24' ignored in --skip-name-resolve mode.
db_nextcloud    | 2021-08-28 18:38:21 0 [Warning] 'proxies_priv' entry '@% root@77cef25aef24' ignored in --skip-name-resolve mode.
db_nextcloud    | 2021-08-28 18:38:21 0 [Note] InnoDB: Buffer pool(s) load completed at 210828 18:38:21
db_nextcloud    | 2021-08-28 18:38:21 0 [Note] mysqld: ready for connections.
db_nextcloud    | Version: '10.6.4-MariaDB-1:10.6.4+maria~focal'  socket: '/run/mysqld/mysqld.sock'  port: 0  mariadb.org binary distribution
db_nextcloud    | 2021-08-28 18:38:22+02:00 [Note] [Entrypoint]: Temporary server started.
db_nextcloud    | Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
db_nextcloud    | Warning: Unable to load '/usr/share/zoneinfo/leapseconds' as time zone. Skipping it.
db_nextcloud    | Warning: Unable to load '/usr/share/zoneinfo/tzdata.zi' as time zone. Skipping it.
db_nextcloud    | 2021-08-28 18:38:25 5 [Warning] 'proxies_priv' entry '@% root@77cef25aef24' ignored in --skip-name-resolve mode.
db_nextcloud    | 2021-08-28 18:38:25+02:00 [Note] [Entrypoint]: Creating database nextcloud
db_nextcloud    | 2021-08-28 18:38:25+02:00 [Note] [Entrypoint]: Creating user nextcloud
db_nextcloud    | 2021-08-28 18:38:25+02:00 [Note] [Entrypoint]: Giving user nextcloud access to schema nextcloud
db_nextcloud    |
db_nextcloud    | 2021-08-28 18:38:25+02:00 [Note] [Entrypoint]: Stopping temporary server
db_nextcloud    | 2021-08-28 18:38:25 0 [Note] mysqld (initiated by: root[root] @ localhost []): Normal shutdown
db_nextcloud    | 2021-08-28 18:38:25 0 [Note] InnoDB: FTS optimize thread exiting.
db_nextcloud    | 2021-08-28 18:38:25 0 [Note] InnoDB: Starting shutdown...
db_nextcloud    | 2021-08-28 18:38:25 0 [Note] InnoDB: Dumping buffer pool(s) to /var/lib/mysql/ib_buffer_pool
db_nextcloud    | 2021-08-28 18:38:25 0 [Note] InnoDB: Buffer pool(s) dump completed at 210828 18:38:25
db_nextcloud    | 2021-08-28 18:38:25 0 [Note] InnoDB: Removed temporary tablespace data file: "./ibtmp1"
db_nextcloud    | 2021-08-28 18:38:25 0 [Note] InnoDB: Shutdown completed; log sequence number 42173; transaction id 15
db_nextcloud    | 2021-08-28 18:38:25 0 [Note] mysqld: Shutdown complete
db_nextcloud    |
db_nextcloud    | 2021-08-28 18:38:26+02:00 [Note] [Entrypoint]: Temporary server stopped
db_nextcloud    |
db_nextcloud    | 2021-08-28 18:38:26+02:00 [Note] [Entrypoint]: MariaDB init process done. Ready for start up.
db_nextcloud    |
db_nextcloud    | 2021-08-28 18:38:26 0 [Note] mysqld (server 10.6.4-MariaDB-1:10.6.4+maria~focal) starting as process 1 ...
db_nextcloud    | 2021-08-28 18:38:26 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
db_nextcloud    | 2021-08-28 18:38:26 0 [Note] InnoDB: Number of pools: 1
db_nextcloud    | 2021-08-28 18:38:26 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
db_nextcloud    | 2021-08-28 18:38:26 0 [Note] mysqld: O_TMPFILE is not supported on /tmp (disabling future attempts)
db_nextcloud    | 2021-08-28 18:38:26 0 [Note] InnoDB: Using Linux native AIO
db_nextcloud    | 2021-08-28 18:38:26 0 [Note] InnoDB: Initializing buffer pool, total size = 134217728, chunk size = 134217728
db_nextcloud    | 2021-08-28 18:38:26 0 [Note] InnoDB: Completed initialization of buffer pool
db_nextcloud    | 2021-08-28 18:38:26 0 [Note] InnoDB: 128 rollback segments are active.
db_nextcloud    | 2021-08-28 18:38:26 0 [Note] InnoDB: Creating shared tablespace for temporary tables
db_nextcloud    | 2021-08-28 18:38:26 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
db_nextcloud    | 2021-08-28 18:38:26 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
db_nextcloud    | 2021-08-28 18:38:26 0 [Note] InnoDB: 10.6.4 started; log sequence number 42173; transaction id 14
db_nextcloud    | 2021-08-28 18:38:26 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
db_nextcloud    | 2021-08-28 18:38:26 0 [Note] Plugin 'FEEDBACK' is disabled.
db_nextcloud    | 2021-08-28 18:38:26 0 [Warning] You need to use --log-bin to make --expire-logs-days or --binlog-expire-logs-seconds work.
db_nextcloud    | 2021-08-28 18:38:26 0 [Note] Server socket created on IP: '0.0.0.0'.
db_nextcloud    | 2021-08-28 18:38:26 0 [Note] InnoDB: Buffer pool(s) load completed at 210828 18:38:26
db_nextcloud    | 2021-08-28 18:38:26 0 [Note] Server socket created on IP: '::'.
db_nextcloud    | 2021-08-28 18:38:26 0 [Warning] 'proxies_priv' entry '@% root@77cef25aef24' ignored in --skip-name-resolve mode.
db_nextcloud    | 2021-08-28 18:38:26 0 [Note] mysqld: ready for connections.
db_nextcloud    | Version: '10.6.4-MariaDB-1:10.6.4+maria~focal'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution

```

If I run a shell inside of the docker container `dsh () { sudo docker exec -it $* /bin/sh; }; dsh nextcloud` and run `occ` I get

```
Nextcloud is not installed - only a limited number of commands are available
Nextcloud 22.1.0

Usage:
  command [options] [arguments]

Options:
  -h, --help            Display this help message
  -q, --quiet           Do not output any message
  -V, --version         Display this application version
      --ansi            Force ANSI output
      --no-ansi         Disable ANSI output
  -n, --no-interaction  Do not ask any interactive question
      --no-warnings     Skip global warnings, show command output only
  -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Available commands:
  check                 check dependencies of the server environment
  help                  Display help for a command
  list                  List commands
  status                show some status information
 app
  app:check-code        check code to be compliant
 integrity
  integrity:check-app   Check integrity of an app using a signature.
  integrity:check-core  Check integrity of core code using a signature.
  integrity:sign-app    Signs an app using a private key.
  integrity:sign-core   Sign core using a private key.
 l10n
  l10n:createjs         Create javascript translation files for a given app
 maintenance
  maintenance:install   install Nextcloud
```
I checked the env variables to be set :
```
/nextcloud $ env | grep ADMIN
ADMIN_PASSWORD=MYADMINPASSWD
ADMIN_USER=admin
```

So I tried  to run the `occ maintenance:install`  and that unveils that these variables seem not to be used:

```
/nextcloud $ occ maintenance:install
What is the password you like to use for the admin account <admin>?
```

When I try to run the install command manually specifying the parameters I need I get
```
occ maintenance:install --admin-user=$ADMIN_USER --admin-pass=$ADMIN_PASSWORD --database=$DB_TYPE --database-name=$DB_NAME --database-host=$DB_HOST --database-user=$DB_USER --database-pass=$DB_PASSWORD
Nextcloud was successfully installed
```
However to get access I have manually to add the fqdn (the content of $DOMAIN env variable ) of the installation in `/nextcloud/config/config.php` 

Shoulddn't all this be done automatically?
