### ISSUE TITLE
Blank files browser in nextcloud web interface

### ISSUE THREAD

**Issue by jmhbnz** [Wonderfall/docker-nextcloud#93]
This morning I updated from Nextcloud 22, to Nextcloud 23. The upgrade was performed by changing the image tag in a docker-compose file and restarting the containers and didn't encounter any issues or unexpected log messages.

After the update, I am now getting a mostly blank `/apps/files/` that does not list any files or external storages (just has the header and left menu).

There are no logs in the container output advising of any errors at the server side or errors in `/data/nextcloud.log` or `/var/log/nginx/error.log`, however there are javascript errors in console:

![Screenshot from 2022-01-23 09-34-37](https://user-images.githubusercontent.com/39425256/150654586-ef733a88-f5c2-466e-a8ea-28e5fe7cec3d.png)

My setup is pretty straightforward, I have nextcloud running via podman-compose on debian 11 with an nginx ingress controller in front acting as a reverse proxy and managing certs via certmanager + lets encrypt.

I've tried both chromium and firefox, and both have the same issue, for separate users.

Here is the proxy configuration I have in front of nextcloud (personal domain replaced with `cloud.example.com`):

```yaml
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: cloud-example-com
  namespace: cloud-example-com
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 10G
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-XSS-Protection: 1";
      more_set_headers "X-Content-Type-Options: nosniff";
      more_set_headers "X-Frame-Options: SAMEORIGIN";
      more_set_headers "Content-Security-Policy: frame-src 'self'; default-src 'self'; script-src 'self' 'unsafe-inline' blob: 'unsafe-eval' https://cloud.example.com https://maxcdn.bootstrapcdn.com https://ajax.googleapis.com; img-src 'self' data: https://secure.gravatar.com; style-src 'self' 'unsafe-inline' https://maxcdn.bootstrapcdn.com https://fonts.googleapis.com; font-src 'self' data: https://maxcdn.bootstrapcdn.com https://fonts.gstatic.com; form-action 'self'; upgrade-insecure-requests";
      more_set_headers "Referrer-Policy: strict-origin-when-cross-origin";
      more_set_headers "Permissions-Policy: geolocation=(none);midi=(self);notifications=(self);push=(self);sync-xhr=();microphone=(none);camera=(none);magnetometer=(none);gyroscope=(none);speaker=(self);vibrate=(self);fullscreen=(self);payment=(none);";
      more_clear_headers "X-Powered-By";
spec:
  tls:
  - hosts:
    - cloud.example.com
    secretName: tls-cloud-example-com
  rules:
  - host: cloud-example-com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nextcloud
            port:
              number: 8888
```

I can browse files fine using android clients, or via DAV. It is only the web interface that is having problems.

Any ideas what might be causing this?
